### ISSUE TITLE
Check street name trim

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#1]
At some point when the output of the script reaches Pelias, it is adding or not removing unnecessary  white space. This white spaces appears in the full "label" property in the JSON results.

**Comment by chriswhong** [comment]
This should happen in the normalization script.  Troubleshoot and ensure that the output does not contain any unnecessary white space.

**Comment by allthesignals** [comment]
Closed by 9d20eb74599ca1de8754000043c124641548da6f
