### ISSUE TITLE
Handle condo lots

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#14]
Condo lots will not have a match in PLUTO, we need the condo's "billing lot".

If the BBL for an address in PAD matches the pattern for condo unit BBL, lookup the corresponding billing BLL in the PAD BBL table (which we have not used to date)

This should happen in the "cleanup" phase

**Comment by allthesignals** [comment]
THis is handled assuch : 

```
pad <- pad %>%
  mutate(
    bbl = case_when(
      (lot >= 1001 & lot <= 6999) | (lot >= 7501 & lot <= 7599) ~ billbbl,
      TRUE                                                      ~ bbl
    )
  )

```

`billbbl` is the concatenated _bill_ boro/block/lot. When the lot is between those two ranges, use billbbl. @chriswhong just need to confirm this
