### ISSUE TITLE
Handle Alternate Street Names

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#15]
For anny PAD address that has more than one LGC, we need to take the additional LGC (LGCs s are two digits, and may look like (0107) concatenate them with the borocode and sc5 to create an 8-digit B7SC.

This 8-digit B7SC becomes the lookup key for the Street Name Dictionary.  The join field in the SND will include 3 additional characters at the end of the field, we are matching the B7SC against only the first 8 characters.

Any matches should become new variants of the original address. 

This should happen after interpolation.

**Comment by allthesignals** [comment]
borocode + sc5 + lgc = a number to lookup in the street name database
