### ISSUE TITLE
Merge adjacent spaces in the middle of addresses

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-geosearch-pad-normalize#18]
Merge multiple adjacent spaces in an address into a single space. 

"519 front east 12 st" should return: 
"519 FRONT EAST 12 STREET" not: 
"519 FRONT EAST&nbsp;&nbsp;&nbsp;12 STREET"

![image](https://user-images.githubusercontent.com/409279/35113785-b50b1e4a-fc50-11e7-8576-1d3210f64cf7.png)

**Comment by andycochran** [comment]
The whitespace causes acceptance tests to fail. 

![image](https://user-images.githubusercontent.com/409279/35114040-6e840170-fc51-11e7-88e4-ad8b372626f3.png)

**Comment by CeciliaCY** [comment]
![capture](https://user-images.githubusercontent.com/30835953/35408035-a273ccb8-0205-11e8-89d4-622a2fdb681d.png)

**Comment by chriswhong** [comment]
Looks like we are cleaning internal white space from the `stname` column in PAD, but we are not doing it for all of the alternate street names in SND.

**Comment by andycochran** [comment]
[PR for this](https://github.com/NYCPlanning/labs-geosearch-pad-normalize/pull/37) is merged should this be closed?
