### ISSUE TITLE
Push to DigitalOcean spaces

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#2]
Script should write a CSV and then push that output to DIgitalOcean spaces, where it will be hosted.

**Comment by chriswhong** [comment]
Add an `npm run deploy` script to the normalization script that will push the output file to DO spaces.

- Check for existence of output file and alert user if it isn't there
- Use `.env` for keys
- Document in `README.md`

**Comment by allthesignals** [comment]
Closed by 9d20eb74599ca1de8754000043c124641548da6f

**Comment by allthesignals** [comment]
It won't use .env for keys because s3cmd can't figure certain things through environment variables
