### ISSUE TITLE
R script creates JSON describing the munging

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-geosearch-pad-normalize#20]
The R script should create a record of what it's done. This could be a JSON file which would allow us to know: 

- How many entries in the raw PAD file
- How many of each rowtype were indexed
- How many entries were excluded* 
- Etc…

The docs site could consume this JSON and display a report with a "totally sweet sankey diagram" (–@chriswhong). 

*Knowing which rows in the original data we aren’t handling will help us decide what we need to do with them or what we could be missing.

**Comment by chriswhong** [comment]
- Modify normalization script to output a JSON file reporting on the normalization.
- timestamp it and push to DO spaces along with the normalized data

**Comment by andycochran** [comment]
We should get the docs site to consume this.
