### ISSUE TITLE
Handle hyphenated addresses that do not have a range

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#22]
Hyphenated addresses need to have their houseNums duplicated so that results show up as "55-02 31 AVENUE" or "5502 31 AVENUE"

We need to add logic inside the sequencing step where `singleAddress` rowtypes are processed.

If the address has a hyphen, add a non-hyphenated version to the houseNums.

**Comment by allthesignals** [comment]
Let's double check this to make sure it's showing up in the export
