### ISSUE TITLE
No Hyphen, Suffix interpolation has some exceptions

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#24]
@andycochran Rodrigo mentioned some exception here, do you remember? It has to do with interpolation 101A - 105D.

**Comment by allthesignals** [comment]
Gonna double check this too

**Comment by andycochran** [comment]
If I remember correctly, this had to do with ranges containing addresses with suffixes that differ in format from the high and low. It was pointed out that while this might be true, it's against the standards and the source data should be fixed. 

@jtalati, I'm gonna go ahead and close this. We can reopen if it comes up again and there are an actionable steps we can take to address the issue.
