### ISSUE TITLE
101 Avenue D (failed) does not return (101 D Avenue works)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#26]
Needs research why this is (is it the geocoder or the normalization).

**Comment by chriswhong** [comment]
"D Avenue" is an alternate street name, the source stname shows "Avenue D".
"101 Avenue D, " will yield an autocomplete result, as it's expecting additional info about borough, etc.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #21](https://github.com/NYCPlanning/labs-geosearch-docker/issues/21) via [**ZenHub**](https://www.zenhub.com/)
