### ISSUE TITLE
1912 Ditmars fails

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#27]
19-12 Ditmars works

**Comment by chriswhong** [comment]
Should be addressed by #11

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #20](https://github.com/NYCPlanning/labs-geosearch-docker/issues/20) via [**ZenHub**](https://www.zenhub.com/)
