### ISSUE TITLE
Research Alternative Street Names

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#3]
Need to join in & further unnest records with multiple alternative street names.

What is necessary here, given our starting dataset?  
Case is Avenue of the Americas is an alternative name for a section of 6th Ave.
-  is this already represented in PAD?
- If not, what would the logic be for figuring out that an address is valid on alternate street names...
- How do we determine the ranges that the alternate street names apply to?

**Comment by chriswhong** [comment]
Handling of alternate street names is outlined in #15
