### ISSUE TITLE
Add custom properties to /search endpoint results

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#32]
Approach:
We can already append custom properties to the documents in the ES database.
We can wrap the Pelias API in another node API that can query the database and append additional properties.

At this point the plan will be to not hijack the autocomplete requests, but only to apply additional properties to /search (which can take longer to return).  Client applications should also be refactored to use /search after an autocomplete result is selected. 

Include other metadata:
Source address range,
BBL,
BIN,
etc

Complete when new express API is deployed and is proxying Pelias requests and adding additional info.

**Comment by andycochran** [comment]
Depends on #31
