### ISSUE TITLE
Check that successful ZoLa searches (Mapzen OSM) still pass

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#41]
We want to make sure we don't regress from the current autocomplete by checking addresses that _are_ successful in ZoLa _still_ work in Geosearch.

Find recent data here: 
https://docs.google.com/spreadsheets/d/1OEU3xBAnliHdXG9AWEpGvKqn6_kJd99SSIPE7ASSlY0/edit#gid=282942988

**Comment by andycochran** [comment]
Closed by https://github.com/NYCPlanning/labs-geosearch-acceptance-tests/commit/af4245e37394f752349ed53d8a1c5bc7b97e7f07.
