### ISSUE TITLE
Exclude rows that should not be imported

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#42]
We currently have console warnings in the script for things like missing lat/lng, missing stname, etc.

If a record has no lat/lng, it does not belong in the geocoder, and should be excluded from the output.

The end state we shoot for is a 1 to 1 match for records in the normalized pad CSV and records in the elasticsearch database.  This will be helpful in troubleshooting the imports.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #17](https://github.com/NYCPlanning/labs-geosearch-docker/issues/17) via [**ZenHub**](https://www.zenhub.com/)
