### ISSUE TITLE
Example address for each rowType

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#47]
We should get some example addresses for each rowType

**Comment by chriswhong** [comment]
Add an acceptance test for each rowtype.

**Comment by andycochran** [comment]
@allthesignals If you use R to can scrape together a list of one random row from each rowType, I can handle writing the tests.

**Comment by allthesignals** [comment]
[sample_types.csv.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969bf0af46b713f3873f046b313916ac217586f76ae5002e005a5c1faa42510947f4ff8d28a6b63d25d8095decd23c4d68d47f40f2ecdd42e64bef62994597b4bc804dc5e93a20e68a8e4c3c1b001d9bb2.zip)

**Comment by allthesignals** [comment]
[sample_types2.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969bf0af46b70fb2d86b56357c2301a03f32dfa17dbe172800595c47fa42505940fff9892af3e469268b5f5affcd7f1d2598694ef1e1c84afd13b032894f8fb7b98b4bc5e93c27e58a8849390c48.zip)
[sample_types3.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969bf0af46b70eb2d86b56357c2301a03f32dfa17dbe172800595c47fa42505940fff9892af3e469268b5f5affcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b4bc5e93c27e58c8c49390c48.zip)
[sample_types4.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969bf0af46b709b2d86b56357c2301a03f32dfa17dbe172800595c47fa42505940fff9892af3e469268b5f5affcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b4bc5e93c27e4898b473d0c48.zip)

**Comment by allthesignals** [comment]
[sample_rowtypes.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969de6a857bd4df5876b0a65633b0ba92e7391a172fd177a545c0e48af480e5c4cfafd8a2ba6b76922df0a0aee807f4366846c4ff8e7df46f554f832815d84bfb68b49c1ef3824e683894f3f1e0d0ac4.zip)
[sample_rowtypes2.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969de6a857bd4df5877b046b313916ac217586f76ae5002e005a5c1faa42510947f4ff8d28a6b63d25d8095decd23c4d68d47f40f2ecdd42e64bef62994597b7b5804dc5e93a20e68a87493b16011e9bb2.zip)
[sample_rowtypes3.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fb9597338e86969de6a857bd4df5877a046b313916ac217586f76ae5002e005a5c1faa42510947f4ff8d28a6b63d25d8095decd23c4d68d47f40f2ecdd42e64bef62994597b7b5804dc5e93a20e68a87483f18001c9bb2.zip)
