### ISSUE TITLE
Need to filter for W, F, and B from the naubflag field, not the addrtype field.

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#55]
Need to filter for W, F, and B from the naubflag field, not the addrtype field.

**Comment by chriswhong** [comment]
From Rodrigo:

> I have further looked into the PAD data that is was provided, tunnels have an addrtype 'T', so they should not have been excluded based on the addrtype filter. Bridges do have an addrtype 'B', however bridges actually do not fall in the category of unnamed buildings. After talking this out with Steve, you need to filter for W, F, and B from the naubflag field, not the addrtype field.

**Comment by jtalati** [comment]
Rodrigo is referring to addrtype B which can also be bridges. A workaround is to have a lookup for B and then filter it out if the naubflag kicks in 'W' 'F' and 'B'. However, Steve said as long as the addrtype 'W' 'F' 'B' are being filtered out its absolutely fine and we dont need to use naubflag.

**Comment by allthesignals** [comment]
@jtalati Gotcha. Can this issue be closed without any changes to the script?

**Comment by jtalati** [comment]
@allthesignals yes closing this issue because what we have is fine since we are filtering out addrtype 'W' 'F' 'B'.
