### ISSUE TITLE
Include information about dataset version #s 

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#57]
We should make sure datasets are sync'd correctly together

**Comment by chriswhong** [comment]
This is related to the `pad_geomtype` attribute, we should have a `pad_version`, `pad_dtm_version`, and `pad_building_footprints_version` appended to every row

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #14](https://github.com/NYCPlanning/labs-geosearch-docker/issues/14) via [**ZenHub**](https://www.zenhub.com/)
