### ISSUE TITLE
Standardize street names from all caps to capitalized

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/labs-geosearch-pad-normalize#58]
Currently, it appears all street names return as all caps (eg. `BROADWAY`) while borough and city return as capitalized (eg. `Manhattan, New York`). This produces strange looking strings out of the box:  
  
`120 BROADWAY, Manhattan, New York, NY, USA`  
  
Not sure why the street name needs to be yelled. 😄

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #13](https://github.com/NYCPlanning/labs-geosearch-docker/issues/13) via [**ZenHub**](https://www.zenhub.com/)
