### ISSUE TITLE
Pull building footprints data from opendata instead of carto

### ISSUE THREAD

**Issue by julialhogan** [NYCPlanning/labs-geosearch-pad-normalize#59]
Instead of using carto `building_footprints` table as source for BIN centroid data, use the data available in opendata: https://data.cityofnewyork.us/Housing-Development/Building-Footprints/nqwf-w8eh

the data is downloadable in centroid format (buildings_p layer, vs buildings layer which includes building footprint centroids) as a CSV via download link: "https://data.cityofnewyork.us/api/views/r94s-f34j/rows.csv?accessType=DOWNLOAD"

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #12](https://github.com/NYCPlanning/labs-geosearch-docker/issues/12) via [**ZenHub**](https://www.zenhub.com/)
