### ISSUE TITLE
Fix "0" addresses (0 BROADWAY)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-geosearch-pad-normalize#6]
Some of the house numbers are set as zero, possibly at the de-nullification step:

> 0 BROADWAY, Manhattan, New York, NY, USA

**Comment by chriswhong** [comment]
Somewhere in the normalization script we are ending up with 0 for the house number, troubleshoot and figure out where these are coming from (and whether there are any legitimate 0 addresses)

**Comment by chriswhong** [comment]
This has been addressed.
