### ISSUE TITLE
Create a PAD Sample Dataset

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#7]
Because the full normalized PAD database will take over an hour to import, we need a subset of PAD that we can use for rapid development.  

This issue is about figuring out how to get a subset that has diversity of address types.

One idea is to base it on the addresses that are in our test suite.  Another is to start with using every Nth row from a normal run of the script.

**Comment by allthesignals** [comment]
Closed by 75d5fc40c045611e567c50d2345e303093b01ad0, this only generates a random sample. We can generate other samples once we know more about the requirements.
