### ISSUE TITLE
Handle non-range Addresses

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#9]
If low and high house numbers match, the row should be included.  No interpolation is necessary, set `housenum` to either the low or high number

**Comment by andycochran** [comment]
I've added an index for this in the "CLASSIFYING ROWS" section. Not sure how to set `housenum`.

**Comment by allthesignals** [comment]
if lhns & hhns are equal, I'm assuming hhnd or hhld will work for the housenum, so we return that.
